apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobefeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kobefeg
  template:
    metadata:
      labels:
        app: kobefeg
    spec:
      containers:
      - image: okteto.dev/kobefeg:latest
        name: kobefeg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "fd85790e-d4de-479b-90f0-5b07c23c8c54"
        - name: Vless_Path
          value: "/fd85790e-d4de-479b-90f0-5b07c23c8c54"
        - name: Vmess_UUID
          value: "b9f6a985-a576-4bca-94ed-983354662e40"
        - name: Vmess_Path
          value: "/b9f6a985-a576-4bca-94ed-983354662e40"
        - name: Share_Path
          value: "/v2link"
